version: '3.2'

networks: 
    postgres-network: 
    grafana-data:
    worker-data: 

volumes: 
    grafana_data:
    influxdb:

services: 
    userdb: 
        image: library/postgres:latest
        volumes: 
            - type: bind
              source: /tmp/pgdata
              target: /var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=flaskapp
            - POSTGRES_PASSWORD=foo
            - POSTGRES_DB=flaskapp
        networks: 
            - postgres-network
        container_name: "userdb"
            
    frontend: 
        build: ./frontend
        ports: 
            - "5000:5000"
        volumes: 
            - type: bind
              source: ./frontend/assets/static
              target: /usr/app/static
            - type: bind
              source: ./frontend/assets/templates
              target: /usr/app/templates
        networks: 
            - postgres-network 
        depends_on: 
            - userdb

    filter-data: 
        image: influxdb:latest
        volumes: 
            - influxdb:/var/lib/influxdb
        environment: 
            - INFLUXDB_DB=filter_data
            - INFLUXDB_USER=worker-node
            - INFLUXDB_USER_PASSWORD=foo
        networks: 
            - worker-data
            - grafana-data

    grafana: 
        image: grafana/grafana:latest
        depends_on: 
            - filter-data
        ports: 
            - "3000:3000"
        volumes: 
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        environment: 
            - GF_SERVER_ROOT_URL=http://grafana.server.name
            - GF_SECURITY_ADMIN_PASSWORD=secret
        networks: 
            - grafana-data

